AsiaLabv1/Controllers/TechnicianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AsiaLabv1.Models;
using AsiaLabv1.Services;

namespace AsiaLabv1.Controllers
{
    public class TechnicianController : Controller
    {
        PatientTestService pts = new PatientTestService();

        public static int _patienttestId,_patientId;
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetPatientInfo()
        {
 
            var patientInfo=pts.GetPatientTests();
            List<RequiredPatient> rp = new List<RequiredPatient>();
             foreach (var item in patientInfo)
                    {
                        rp.Add(new RequiredPatient
                        {
                           //Id=item.PatientId,
                           //PatientName=item.Patient.PatientName,
                           //PatientNumber=item.Patient.PatientNumber
                           Id=item.Id,
                           PatientName=item.PatientName,
                           PatientNumber=item.PatientNumber

                        });
                    }
                    return Json(rp, JsonRequestBehavior.AllowGet);

          }

        public ActionResult PerformTest()
        {
            return View();
        }

        public void Temp(string patientId)
        {
            _patientId = Convert.ToInt16(patientId);
            TempData["ID"] = patientId;
        }

        public ActionResult GetTests()
        {

            var patientDetails = pts.GetPatientTestsById(Convert.ToInt16(TempData["ID"]));
            List<RequiredTechnicianItems> TechnicianItems = new List<RequiredTechnicianItems>();
            List<RequiredTest> rt = new List<RequiredTest>();

                _patienttestId = patientDetails[0].Id;
                var pno = patientDetails[0].Patient.PatientNumber;
                var pname = patientDetails[0].Patient.PatientName;
                var ptests = patientDetails[0].Patient.PatientTests;

                foreach (var item2 in ptests)
                {

                    rt.Add(new RequiredTest
                    {
                        
                        Id=item2.TestSubcategory.Id,
                        testName=item2.TestSubcategory.TestSubcategoryName,
                        lowerBound=item2.TestSubcategory.LowerBound,
                        upperBound=item2.TestSubcategory.UpperBound,
                        unit=item2.TestSubcategory.Unit

                    });
                   
                }

                TechnicianItems.Add(new RequiredTechnicianItems { 
                
                PatientNumber=pno,
                PatientName=pname,
                PatientTests=rt
                
                
                });
            

            return Json(TechnicianItems,JsonRequestBehavior.AllowGet);
        }

        public ActionResult TestResults(string[] result)
        {
            int id = _patienttestId;
            for (int i = 0; i < result.Length; i++)
            {
                pts.InsertPatientTestResults(new PatientTestResult { 
                
                PatientTestId=id,
                Result=result[i],
                ApprovalStatus="Not Approved",
                Remarks="Remarksss",

                });

            }

            pts.InsertTechnicianPatientTests(new TechnicianPatientsTest
            {

                TechnicianId = Convert.ToInt16(Session["loginuser"]),
                Dated = DateTime.Now,
                PatientId = _patientId,

            });


            return RedirectToAction("TechnicianDashboard","Main");
        }
        

    }
}

AsiaLabv1/Views/Technician/PerformTest.cshtml
@{
    ViewBag.Title = "PerformTest";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@section Banner
{
    <div class="banner">

        <h2>
            <a href="index.html">Home</a>
            <i class="fa fa-angle-right"></i>
            <span>Perform Test</span>
        </h2>
    </div>
}

@*---------Start Side Navigation Menu-----------*@

@section NavMenu
{
    <li>
        <a href="@Url.Action("TechnicianDashboard", "Main")" class=" hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Dashboard</span> </a>
    </li>

    <li><a href="@Url.Action("PerformTest", "Technician")" class=" hvr-bounce-to-right"><i class="fa fa-desktop nav_icon"></i>Perform Test</a></li>





}
@*------------ End Side Navigation Menu----------*@


@*------------- Start Main Content Code-------------*@

<div class="grid-form">

    <!----->
    <!---->
    <div class="grid-form1">

        <div class="tab-content">

            <div class="tab-pane active" id="horizontal-form">

                <div class="horz-grid">
                    <div class="grid-hor" id="patientinfo">
                        <h4 id="grid-example-mixed-complete">Perform Test</h4><br />
                       

                    </div>
                    <!---->

                    <div class="row show-grid">
                        <div class="col-xs-6 col-sm-3">Test Name</div>
                        <div class="col-md-1">Result</div>

                        <div class="col-xs-6 col-sm-3">Lower Bound</div>
                        <div class="col-xs-6 col-sm-3">Upper Bound</div>
                        <div class="col-md-1">Unit</div>


                    </div>
                    <div style="border: 2px; border-style: solid;  color: #d95459; ">

                    </div>



                    <div class="row show-grid" id="tests">

                    </div>

                    


                </div>


                <div class="col-sm-2 login-do" style="margin-left:40%">
                    <label class="hvr-shutter-in-horizontal login-sub">
                        <input type="button" id="btninsert" value="Submit Test" />
                    </label>
                </div>


                <div class="clearfix"> </div>
                
            </div>
        </div>
    </div>
</div>
<br /><br /><br />


<script type="text/javascript">

    window.onload = getTests;

    function getTests(){

            $.ajax({
                type: 'GET',
                url: '/Technician/GetTests/',
                dataType: "json",
                success: function (data) {
                    
                    $('#patientinfo').append('<h5 id="grid-example-mixed-complete">Patient No. ' + data[0].PatientNumber + '</h5>');
                    $('#patientinfo').append('<h5 id="grid-example-mixed-complete">Patient Name: '+ data[0].PatientName+'</h5>');

                    for (var i = 0; i < data[0].PatientTests.length; i++) {
                      
                        $('#tests').append('<div class="col-xs-6 col-sm-3" id="testname'+i+'">' + data[0].PatientTests[i].testName + '<br /></div>');
                        $('#tests').append('<div class="col-md-1"  id="testresult' + i + '"><input type="text" class="form-control" id="focusedinput' + i + '"/"></div>');
                        $('#tests').append('<div class="col-xs-6 col-sm-3" id="testlowerbound' + i + '">' + data[0].PatientTests[i].lowerBound + '</div>');
                        $('#tests').append('<div class="col-xs-6 col-sm-3"  id="testupperbound' + i + '">' + data[0].PatientTests[i].upperBound + '</div>');
                        $('#tests').append('<div class="col-md-1"  id="testunit' + i + '">' + data[0].PatientTests[i].unit + '<br /></div>');
                       
                    }
                },
                error: function (data) {
                    alert('Error');
                }
            });

    }

    $('#btninsert').click(function () {

        var inputCount = document.getElementById('tests').getElementsByTagName('input').length;
        var results = [];
       
        for (var i = 0; i < inputCount; i++) {
         
            testresult=$('#focusedinput'+i).val(),
            results.push(testresult);
        }


        $.ajax({

            type: 'POST',
            url: '/Technician/TestResults/',
            traditional: true,
            data: { result: results },
            dataType: "json",
           
        });

      
    });



</script>

<!--//grid-->
@*------------- End Main Content Code-------------*@