AsiaLabv1/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AsiaLabv1.Controllers
{
    public class DoctorController : Controller
    {
        //
        // GET: /Doctor/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ApproveTest()
        {
            return View();
        }

       


    }
}

AsiaLabv1/Controllers/MainController.cs
using AsiaLabv1.Models;
using AsiaLabv1.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AsiaLabv1.Controllers
{
    public class MainController : Controller
    {

        //this class is used for user/employee related queries
        //any query related to employee has been written in this class
        UserService UsersService = new UserService();
        BranchService BranchesService = new BranchService();

        public ActionResult LoginPage()
        {
            return View("LoginPage");
        }

        public ActionResult Khaali()
        {
            return View();
        }

        public ActionResult EditProfile()
        {
            return View();
        }

        public ActionResult AdminDashboard()
        {
            return View();
        }
        public ActionResult DoctorDashboard()
        {
            return View();
        }
        public ActionResult ReceptionistDashboard()
        {
            return View();
        }
        public ActionResult TechnicianDashboard()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection LoginForm)
        {

            /*
             * for admin login and password
                username: testadmin
                password: admin2016
             * for reciptionist login and password
                username:  TestReceiptionist
                password:  TestReceiptionist2016
             */


            #region commented bekar code baad m delete krdengy ye
            //UsersService.AddUserType("Admin");
            //UsersService.AddUserType("Doctor");
            //UsersService.AddUserType("Receptionist");
            //UsersService.AddUserType("Technician");

            //BranchesService.AddBranch("branch1name", "branch 1 address", "Br Code");

            //UsersService.AddUser();
         //   var t = UsersService.GetAllUserTypes();
          //  var a = BranchesService.GetAllBranches();

           // UsersService.AddUser();
            //var t = UsersService.GetAllUserTypes();
            // var a = BranchesService.GetAllBranches();
            #endregion

            string username = LoginForm["Email"].ToString();
            string password = LoginForm["Password"].ToString();

            var model = UsersService.ValidateLogin(username, password);

            if (model==null)
            {
                return RedirectToAction("LoginPage", "Main");

            }
            

            if (model != null)
            {
                Session["loginuser"] = model.Id;
                Session["loginusername"] = model.Name;
                Session["name"] = model.Name;
                Session["role"] = model.UserRole;

                if (model.Name == "Humam admin")
                {
                    Session["AdminLabelShow"] = model.Name;
                }
                
                Session["branch"] = model.BranchName;
                return View(model.UserRole + "Dashboard", model);
            }

            return RedirectToAction("LoginPage");
        }

        public ActionResult abc()
        {
            return View();
        }


        public ActionResult LogOut()
        {
            Session["loginuser"] = null;
            Session["loginusername"] = null;
            Session["AdminLabelShow"] = null;
            return RedirectToAction("LoginPage");
        }

    }
}

AsiaLabv1/Controllers/ReciptionistController.cs
using AsiaLabv1.Models;
using AsiaLabv1.Services;
using MigraDoc.DocumentObjectModel;
using MigraDoc.Rendering;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AsiaLabv1.Controllers
{
    public class ReciptionistController : Controller
    {
        UserService UserServices = new UserService();
        PatientService PatientServices = new PatientService();
        PatientTestService PatientTestService = new PatientTestService();
        GenderService GenderServices = new GenderService();
        TestDeptService TestDeptServices = new TestDeptService();
        TestCategoryService TestCategoryServices = new TestCategoryService();
        TestSubCategoryService TestSubCategoryServices = new TestSubCategoryService();
        ReferDoctorsService ReferDoctorsServices = new ReferDoctorsService();
        PatientPaymentService PatientPaymentServices = new PatientPaymentService();
        BranchService BranchServices = new BranchService();

        public ActionResult RegisterPatient()
        {
            var model = new PatientModel();
            var Genders = GenderServices.GetAll();
            foreach (var item in Genders)
            {
                model.Genders.Add(new SelectListItem
                {
                    Text = item.GenderDescription,
                    Value = item.Id.ToString()
                });
            }
            var allDept = TestDeptServices.GetAllDept();

            foreach (var Dept in allDept)
            {
                model.Departments.Add(new SelectListItem
                {
                    Value = Dept.Id.ToString(),
                    Text = Dept.DepartmentName
                });
            }

            var allrefers = ReferDoctorsServices.GetAllReferDoctors();
            foreach (var refer in allrefers)
            {
                model.ReferredDoctors.Add(new SelectListItem
                {
                    Value = refer.Id.ToString(),
                    Text = refer.ReferredDoctorName
                });
            }

            var Paytypes = PatientPaymentServices.GetAllPayTypes();
            foreach (var Paytype in Paytypes)
            {
                model.PayTypes.Add(new SelectListItem
                {
                    Value = Paytype.Id.ToString(),
                    Text = Paytype.Description
                });
            }

            return View("RegisterPatient", model);
        }

        [HttpPost]
        public ActionResult GetTests(int Id)
        {
            var Tests = TestSubCategoryServices.GetSubCategTestsByTestCategoryId(Id);
            var TestList = new List<TestSubCategoryModel>();
            
            #region for test code delete later
            //for (int i = 0; i < 10; i++)
            //{
            //    TestList.Add(new TestSubCategoryModel
            //    {
            //        Id = i,
            //        Rate = i*5,
            //        TestSubcategoryName = "Testname"+i.ToString()
            //    });
            //}
            #endregion

            foreach (var item in Tests)
            {
                TestList.Add(new TestSubCategoryModel
                {
                    Id = item.Id,
                    Rate = item.Rate,
                    TestSubcategoryName = item.TestSubcategoryName
                });
            }

            return Json(TestList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetSubCategory(int Id)
        {
            var TestList = TestCategoryServices.GetTestCategoryByDeptId(Id);
            var TestsList = new List<Tests>();
            foreach (var item in TestList)
            {
                TestsList.Add(new Tests
                {
                    Id = item.Id,
                    Name = item.TestName
                });
            }
            return Json(TestsList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddPatient(PatientModel model)
        {

            #region temp code this must be removed
            //PatientPaymentServices.AddPayType(new PayType
            //{
            //    Description = "Card"
            //});
            //PatientPaymentServices.AddPayType(new PayType
            //{
            //    Description = "Cash"
            //});
            #endregion
            #region testing code should be delete
            //var model=new PatientModel(){
            //    BranchId=1,
            //    Name="firstTestPatient",
            //    Email="Testpatient@gmail.com",
            //    GenderId=1,
            //    DateofBirth=DateTime.Now,
            //    PhoneNumber="987987697",
            //    ReferredId=-1
            //};
            #endregion

            if (model.PatientTestIds.Count > 0)
            {
                int UserId = Convert.ToInt32(Session["loginuser"].ToString());
                var branch = UserServices.GetUserBranch(UserId);
                model.BranchId = branch.Id;
                PatientServices.Add(model);
                List<TestSubcategory> selectedTests = new List<TestSubcategory>();
                double netAmount = 0;
                foreach (var TestId in model.PatientTestIds)
                {
                    PatientTestService.Add(new PatientTest
                    {
                        PatientId = model.Id,
                        TestSubcategoryId = TestId
                    });
                    var test = TestSubCategoryServices.getById(TestId);
                    selectedTests.Add(test);
                    netAmount = netAmount + test.Rate;
                }
               
                if (model.Discount > 0)
                {
                    netAmount = netAmount - model.Discount;
                }

                PatientPaymentServices.Add(new Payment
                {
                    PatientId = model.Id,
                    PatientName = model.Name,
                    PaidAmount = model.PaidAmount,
                    Discount = model.Discount,
                    NetAmount = netAmount,
                    Balance = model.PaidAmount - netAmount,
                    PayTypeId = model.PayId
                });
                
                var gender = GenderServices.GetById(model.GenderId);
                
                model.Genders.Add(new SelectListItem
                {
                    Text = gender.GenderDescription
                });
                
                var referdoctor = ReferDoctorsServices.GetReferDoctorById(model.ReferredId);
                
                model.ReferredDoctors.Add(new SelectListItem
                {
                    Text = referdoctor.ReferredDoctorName
                });
                var branchContact = BranchServices.GetBranchContact(branch.Id);
                GeneratePdf(model, selectedTests,branch,branchContact);

                return Json("SuccessFully Added Patient", JsonRequestBehavior.AllowGet);
            }
            return Json("Please assign tests to patients", JsonRequestBehavior.AllowGet);
            
        }

        [NonAction]
        public void GeneratePdf(PatientModel model,List<TestSubcategory> tests,Branch branch,Contact branchcontact)
        {
            var path = Server.MapPath("/images/");
            // Create a invoice form with the sample invoice data
            PatientRecipt patient = new PatientRecipt(path, model, tests,branch,branchcontact);

            // Create a MigraDoc document
            Document document = patient.CreateDocument();
            document.UseCmykColor = true;


            // Create a renderer for PDF that uses Unicode font encoding
            PdfDocumentRenderer pdfRenderer = new PdfDocumentRenderer(true);

            // Set the MigraDoc document
            pdfRenderer.Document = document;

            // Create the PDF document
            pdfRenderer.RenderDocument();

            // Save the PDF document...
            string filename = "Patient-"+model.Id+".pdf";
            //#if DEBUG
            //    // I don't want to close the document constantly...
            //    filename = "Patient-" + Guid.NewGuid().ToString("N").ToUpper() + ".pdf";
            //#endif

            pdfRenderer.Save(Server.MapPath("/PatientsReport/") + filename);
            // ...and start a viewer.
            Process.Start(Server.MapPath("/PatientsReport/") + filename);


           // PdfDocument pdf = new PdfDocument();
           // PdfPage pdfPage = pdf.AddPage();
           // XGraphics graph = XGraphics.FromPdfPage(pdfPage);
           // XFont font = new XFont("Verdana", 20, XFontStyle.Bold);
           //// graph.DrawRectangle(XBrushes.BlueViolet, new RectangleF(0, 0, 100, 50));
           // graph.DrawString("This is my first PDF document", font, XBrushes.Black,
           // new XRect(0, 0, pdfPage.Width.Point, pdfPage.Height.Point), XStringFormats.Center);
           // pdf.Save("firstpage.pdf");
            
        }

       

    }
}

AsiaLabv1/Views/Main/AdminDashboard.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@model AsiaLabv1.Models.UserModel

@section Banner
{
    @*<div class="banner">

            <h2>
                <a href="index.html">Home</a>
                <i class="fa fa-angle-right"></i>
                <span>Admin Dashboard</span>
            </h2>
        </div>*@
}

@*---------Start Side Navigation Menu-----------*@

@section NavMenu
{
    <li>
        <a href="@Url.Action("AdminDashboard","Main")" class=" hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Dashboard</span> </a>
    </li>

    <li class="active">
        <a href="@Url.Action("TestsManagement","Admin")" class=" hvr-bounce-to-right"><i class="fa fa-indent nav_icon"></i> <span class="nav-label">Tests Management</span></a>

    </li>
    <li>
        <a href="@Url.Action("DoctorReferrals", "Admin")" class=" hvr-bounce-to-right"><i class="fa fa-desktop nav_icon"></i> <span class="nav-label">Doctor Referrals</span></a>
    </li>
    <li>
        <a href="@Url.Action("Register","Admin")" class=" hvr-bounce-to-right"> <i class="fa fa-indent nav_icon"></i>Employee Management</a>
    </li>
<li>
    <a href="@Url.Action("Templates","Admin")" class="hvr-bounce-to-right"> <i class="fa fa-indent nav_icon"></i>Templates</a>
</li>

    <li>
        <a href="@Url.Action("Accounting", "Admin")" class=" hvr-bounce-to-right"><i class="fa fa-th nav_icon"></i> <span class="nav-label">Accounting</span> </a>
    </li>

    <li>
    <li>
        <a href="@Url.Action("BranchReport", "Admin")" class=" hvr-bounce-to-right"> <i class="fa fa-area-chart nav_icon"></i>Branch Report</a>
    </li>

}
@*------------ End Side Navigation Menu----------*@


@*------------- Start Main Content Code-------------*@

<div class="content-top">
    <div class="col-md-8 content-top-2">
        <!---start-chart---->
        <!----->

    </div>

</div>
<!---->


<div class="content-mid">


    <div class="col-md-6">
        <div class="weather">
            <div class="weather-top">
                <div class="weather-top-left">
                    <div class="degree">
                        <figure class="icons">
                            <canvas id="partly-cloudy-day" width="64" height="64"></canvas>
                        </figure>
                        <span>37°</span>
                        <div class="clearfix"></div>
                    </div>
                    <script>
                        var icons = new Skycons({ "color": "#1ABC9C" }),
                             list = [
                               "clear-night", "partly-cloudy-day",
                               "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
                               "fog"
                             ],
                             i;

                        for (i = list.length; i--;)
                            icons.set(list[i], list[i]);

                        icons.play();
                    </script>
                    <p>
                        FRIDAY
                        <label>13</label>
                        <sup>th</sup>
                        AUG
                    </p>
                </div>
                <div class="weather-top-right">
                    <p><i class="fa fa-map-marker"></i>lorem ipsum</p>
                    <label>lorem ipsum</label>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="weather-bottom">
                <div class="weather-bottom1">
                    <div class="weather-head">
                        <h4>Cloudy</h4>
                        <figure class="icons">
                            <canvas id="cloudy" width="58" height="58"></canvas>
                        </figure>
                        <script>
                            var icons = new Skycons({ "color": "#999" }),
                                 list = [
                                   "clear-night", "cloudy",
                                   "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
                                   "fog"
                                 ],
                                 i;

                            for (i = list.length; i--;)
                                icons.set(list[i], list[i]);

                            icons.play();
                        </script>
                        <h6>20°</h6>
                        <div class="bottom-head">
                            <p>August 16</p>
                            <p>Monday</p>
                        </div>
                    </div>
                </div>
                <div class="weather-bottom1 ">
                    <div class="weather-head">
                        <h4>Sunny</h4>
                        <figure class="icons">
                            <canvas id="clear-day" width="58" height="58"></canvas>
                        </figure>
                        <script>
                            var icons = new Skycons({ "color": "#999" }),
                                 list = [
                                   "clear-night", "clear-day",
                                   "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
                                   "fog"
                                 ],
                                 i;

                            for (i = list.length; i--;)
                                icons.set(list[i], list[i]);

                            icons.play();
                        </script>
                        <h6>37°</h6>
                        <div class="bottom-head">
                            <p>August 17</p>
                            <p>Tuesday</p>
                        </div>
                    </div>
                </div>
                <div class="weather-bottom1">
                    <div class="weather-head">
                        <h4>Rainy</h4>
                        <figure class="icons">
                            <canvas id="sleet" width="58" height="58"></canvas>
                        </figure>
                        <script>
                            var icons = new Skycons({ "color": "#999" }),
                                 list = [
                                   "clear-night", "clear-day",
                                   "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
                                   "fog"
                                 ],
                                 i;

                            for (i = list.length; i--;)
                                icons.set(list[i], list[i]);

                            icons.play();
                        </script>

                        <h6>7°</h6>
                        <div class="bottom-head">
                            <p>August 18</p>
                            <p>Wednesday</p>
                        </div>
                    </div>
                </div>
                <div class="weather-bottom1 ">
                    <div class="weather-head">
                        <h4>Snowy</h4>
                        <figure class="icons">
                            <canvas id="snow" width="58" height="58"></canvas>
                        </figure>
                        <script>
                            var icons = new Skycons({ "color": "#999" }),
                                 list = [
                                   "clear-night", "clear-day",
                                   "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
                                   "fog"
                                 ],
                                 i;

                            for (i = list.length; i--;)
                                icons.set(list[i], list[i]);

                            icons.play();
                        </script>
                        <h6>-10°</h6>
                        <div class="bottom-head">
                            <p>August 16</p>
                            <p>Thursday</p>
                        </div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>

        </div>
    </div>
    <div class="clearfix"> </div>
</div>
<!----->
<div class="content-bottom">
    <div class="col-md-6 post-top">

        <div class="post-bottom">
            <div class="post-bottom-1">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <p>15k <label>Likes</label></p>
            </div>
            <div class="post-bottom-2">
                <a href="#"><i class="fa fa-twitter"></i></a>
                <p>20M <label>Followers</label></p>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>

    <div class="clearfix"> </div>
</div>
@*------------- End Main Content Code-------------*@

AsiaLabv1/Views/Main/DoctorDashboard.cshtml
@{
    ViewBag.Title = "DoctorDashboard";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@model AsiaLabv1.Models.UserModel
@section Banner
{
    @*<div class="banner">

        <h2>
            <a href="index.html">Home</a>
            <i class="fa fa-angle-right"></i>
            <span>Approve Test</span>
        </h2>
    </div>*@
}

@*---------Start Side Navigation Menu-----------*@

@section NavMenu
{
    <li>
    <a href="@Url.Action("DoctorDashboard","Main")" class=" hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Dashboard</span> </a>
</li>

<li><a href="@Url.Action("ApproveTest","Doctor")" class=" hvr-bounce-to-right"><i class="fa fa-desktop nav_icon"></i>Approve Test</a></li>


}
@*------------ End Side Navigation Menu----------*@


@*------------- Start Main Content Code-------------*@

<div class="content-top">


    <div class="col-md-4 ">
        <div class="content-top-1">
            <div class="col-md-6 top-content">
                <h5>Tests Pending for Approval</h5>
                <label>19</label>
            </div>
            <div class="col-md-6 top-content1">
                <div id="demo-pie-1" class="pie-title-center" data-percent="25"> <span class="pie-value"></span> </div>
            </div>
            <div class="clearfix"> </div>
        </div>

    </div>
    <div class="col-md-8 content-top-2">
        <!---start-chart---->
        <!----->

    </div>
    <div class="clearfix"> </div>
</div>
<!---->
<div class="typo-grid">

    <div class="typo-1" s>


        <div class="grid_3 grid_5">

            <div class="but_list">
                <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
                    <ul id="myTab" class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Pending</a></li>
                        <li role="presentation"><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile">Search Tests</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">


                            <div class="tab-content">

                                <div class="tab-pane active" id="horizontal-form">
                                    <div class="horz-grid">
                                        <div class="grid-hor">
                                            <h4 id="grid-example-mixed-complete">Pending Tests List for Approval </h4>

                                        </div>
                                        <!---->

                                        <div class="row show-grid">
                                            <div class="col-xs-6 col-sm-3">Patient no.</div>
                                            <div class="col-xs-6 col-sm-3">Patient Name</div>
                                            <div class="col-xs-6 col-sm-3">Test Options</div>
                                        </div>
                                        <div class="row show-grid">
                                            <div class="col-xs-6 col-sm-3">1008</div>
                                            <div class="col-xs-6 col-sm-3">Shahzad</div>

                                            <div class="col-xs-6 col-sm-3">
                                                &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                <button type="button" class="btn btn-xs btn-danger" onclick="window.location='PerformTest.html';">Approve Test</button>

                                            </div>


                                        </div>
                                        <div class="row show-grid">
                                            <div class="col-xs-6 col-sm-3">1009</div>
                                            <div class="col-xs-6 col-sm-3">Akhtar</div>

                                            <div class="col-xs-6 col-sm-3">
                                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                <button type="button" class="btn btn-xs btn-danger" onclick="window.location = 'PerformTest.html';">Approve Test</button>

                                            </div>


                                        </div>


                                    </div>

                                </div>
                            </div>


                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">

                            <h3>Search Tests By Date</h3>
                            <div class="tab-content">

                                <div class="tab-pane active" id="horizontal-form">

                                    <form class="form-horizontal">
                                        <br />
                                        <div class="form-group">
                                            <label for="pname" class="col-sm-2 control-label">From Date</label>
                                            <div class="col-sm-8">
                                                <input type="date" class="form-control1" id="focusedinput">
                                            </div>

                                        </div>
                                        <div class="form-group">
                                            <label for="pname" class="col-sm-2 control-label">To Date</label>
                                            <div class="col-sm-8">
                                                <input type="date" class="form-control1" id="focusedinput">
                                            </div>

                                        </div>

                                        <div class="col-sm-2 login-do" style="margin-left:40%">
                                            <label class="hvr-shutter-in-horizontal login-sub">
                                                <input type="submit" value="See Tests" onclick="window.location='signup.html';" />
                                            </label>
                                        </div>
                                        <br /><br /><br /><br /><br />

                                        <br />


                                        <div class="clearfix"> </div>
                                    </form>

                                </div>

                            </div>


                        </div>


                    </div>

                </div>
            </div>
        </div>
    </div>



</div>

<!----->
<!--//content-->
@*------------- End Main Content Code-------------*@

AsiaLabv1/Views/Main/ReceptionistDashboard.cshtml
@{
    ViewBag.Title = "ReceptionistDashboard";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@model AsiaLabv1.Models.UserModel
@section Banner
{
    <div class="banner">

        <h2>
            <a href="index.html">Home</a>
            <i class="fa fa-angle-right"></i>
            <span>Dashboard</span>
        </h2>
    </div>
}

@*---------Start Side Navigation Menu-----------*@

@section NavMenu
{
  <li>
    <a href="@Url.Action("ReceptionistDashboard","Main")" class=" hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Dashboard</span> </a>
</li>



<li><a href="@Url.Action("RegisterPatient", "Reciptionist" )" class=" hvr-bounce-to-right"><i class="fa fa-desktop nav_icon"></i>Accept Test</a></li>
<li><a href="@Url.Action("PrintReport", "Reciptionist")" class=" hvr-bounce-to-right"><i class="fa fa-file-text-o nav_icon"></i>Print Report</a></li>




}
@*------------ End Side Navigation Menu----------*@


@*------------- Start Main Content Code-------------*@

<div class="blank">


</div>

@*------------- End Main Content Code-------------*@